name: caption_craft
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1

  # Helpers
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  fpdart: ^1.1.0
  google_generative_ai: ^0.4.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  mime: ^1.0.5
  envied: ^0.5.4+1

  # UI & Animations
  liquid_swipe: ^3.1.0
  dotted_border: ^2.1.0
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.2
  pie_menu: ^3.2.1
  flutter_animate: ^4.5.0
  avatar_glow: ^3.0.1

  # Firebase
  firebase_core: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  envied_generator:
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 800

    - family: Danfo
      fonts:
        - asset: assets/fonts/Danfo-Regular.ttf
